### ISSUE TITLE
Old Dotfiles

### ISSUE THREAD

**Issue by Jordan-Jay** [A-Siam/dotfiles#1]
Do you still have the dotfiles from this post? https://www.reddit.com/r/unixporn/comments/hb66ce/bspwm_first_day_with_bspwm/

**Comment by ak-seyam** [comment]
Nope, If you want to ask me anything feel free to do tho

**Comment by Jordan-Jay** [comment]
What's the icon theme you used for the Polybar in the screenshots? If you remember

**Comment by ak-seyam** [comment]
I think it was font awesome 5
